import { LANGUAGE, RES_KEY, TRANSLATION_NS } from "src/common/constants/app";

export const translates = [
	// error
	{
		lang: LANGUAGE.EN,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.UNKNOWN.message,
		value: "Unknown error",
	},
	{
		lang: LANGUAGE.VI,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.UNKNOWN.message,
		value: "Loi khong xac dinh",
	},
	{
		lang: LANGUAGE.EN,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.VALIDATION.message,
		value: "Validation data failed",
	},
	{
		lang: LANGUAGE.VI,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.VALIDATION.message,
		value: "Thong tin gui len khong hop le",
	},
	{
		lang: LANGUAGE.EN,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.NOT_FOUND.message,
		value: "Not found",
	},
	{
		lang: LANGUAGE.VI,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.NOT_FOUND.message,
		value: "Khong tim thay duong dan",
	},
	{
		lang: LANGUAGE.EN,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.INTERNAL_SERVER_ERROR.message,
		value: "Internal server error",
	},
	{
		lang: LANGUAGE.VI,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.INTERNAL_SERVER_ERROR.message,
		value: "Loi khong xac dinh",
	},
	{
		lang: LANGUAGE.EN,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.UN_AUTHORIZATION.message,
		value: "Un authorization",
	},
	{
		lang: LANGUAGE.VI,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.UN_AUTHORIZATION.message,
		value: "Loi xac thuc nguoi dung",
	},
	{
		lang: LANGUAGE.EN,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.EMAIL_ALREADY_EXIST.message,
		value: "Email already exist",
	},
	{
		lang: LANGUAGE.VI,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.EMAIL_ALREADY_EXIST.message,
		value: "Email da ton tai",
	},
	{
		lang: LANGUAGE.EN,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.USERNAME_ALREADY_EXIST.message,
		value: "Username already exist",
	},
	{
		lang: LANGUAGE.VI,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.USERNAME_ALREADY_EXIST.message,
		value: "Username da ton tai",
	},
	{
		lang: LANGUAGE.EN,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.USER_NOT_FOUND.message,
		value: "User not found",
	},
	{
		lang: LANGUAGE.VI,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.USER_NOT_FOUND.message,
		value: "Khong tim thay nguoi dung",
	},
	{
		lang: LANGUAGE.EN,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.USER_PASSWORD_ATTEMPT_MAX.message,
		value: "Maximum password attempts",
	},
	{
		lang: LANGUAGE.VI,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.USER_PASSWORD_ATTEMPT_MAX.message,
		value: "So lan thu mat khau toi da",
	},
	{
		lang: LANGUAGE.EN,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.USER_PASSWORD_NOT_MATCH.message,
		value: "Password not match",
	},
	{
		lang: LANGUAGE.VI,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.USER_PASSWORD_NOT_MATCH.message,
		value: "Sai mat khau",
	},
	{
		lang: LANGUAGE.EN,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.USER_INACTIVE.message,
		value: "User inactive",
	},
	{
		lang: LANGUAGE.VI,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.USER_INACTIVE.message,
		value: "Nguoi dung chua kich hoat",
	},
	{
		lang: LANGUAGE.EN,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.USER_INACTIVE.message,
		value: "User inactive permanent",
	},
	{
		lang: LANGUAGE.VI,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.USER_INACTIVE_PERMANENT.message,
		value: "Nguoi dung khong hoat dong vinh vien",
	},
	{
		lang: LANGUAGE.EN,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.USER_BLOCKED.message,
		value: "User blocked",
	},
	{
		lang: LANGUAGE.VI,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.USER_BLOCKED.message,
		value: "Nguoi dung da bi chan",
	},
	{
		lang: LANGUAGE.EN,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.USER_PASSWORD_EXPIRED.message,
		value: "Password expired",
	},
	{
		lang: LANGUAGE.VI,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.USER_PASSWORD_EXPIRED.message,
		value: "Mat khau da het han",
	},
	{
		lang: LANGUAGE.EN,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.WRONG_TOKEN.message,
		value: "Wrong token",
	},
	{
		lang: LANGUAGE.VI,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.WRONG_TOKEN.message,
		value: "Token loi",
	},
	{
		lang: LANGUAGE.EN,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.TOKEN_EMPTY.message,
		value: "Token empty",
	},
	{
		lang: LANGUAGE.VI,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.TOKEN_EMPTY.message,
		value: "Thieu token",
	},
	{
		lang: LANGUAGE.EN,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.TOKEN_EXPIRED.message,
		value: "Token has been expired",
	},
	{
		lang: LANGUAGE.VI,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.TOKEN_EXPIRED.message,
		value: "Token da het han",
	},
	{
		lang: LANGUAGE.EN,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.MAINTENANCE.message,
		value: "Server maintenance",
	},
	{
		lang: LANGUAGE.VI,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.MAINTENANCE.message,
		value: "Server dang trong qua trinh bao tri",
	},
	{
		lang: LANGUAGE.EN,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.ACTIVE_ACCOUNT_EMAIL_RATE_LIMIT.message,
		value: "Please wait 5 minutes before retry send email again",
	},
	{
		lang: LANGUAGE.VI,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.ACTIVE_ACCOUNT_EMAIL_RATE_LIMIT.message,
		value: "Vui long kiem tra hop thu truoc khi yeu cau gui email moi",
	},
	{
		lang: LANGUAGE.EN,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.SETTING_ALREADY_EXIST.message,
		value: "Setting with key {{key}} has been exist",
	},
	{
		lang: LANGUAGE.VI,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.SETTING_ALREADY_EXIST.message,
		value: "Cai dat {{key}} da ton tai",
	},
	{
		lang: LANGUAGE.EN,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.SETTING_VALUE_NOT_ALLOWED_ERROR.message,
		value: "Setting value not allowed",
	},
	{
		lang: LANGUAGE.VI,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.SETTING_VALUE_NOT_ALLOWED_ERROR.message,
		value: "Gia tri cai dat khong hop le",
	},
	{
		lang: LANGUAGE.EN,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.SETTING_NOT_FOUND.message,
		value: "Setting not found",
	},
	{
		lang: LANGUAGE.VI,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.SETTING_NOT_FOUND.message,
		value: "Khong tim thay cai dat",
	},

	// response
	{
		lang: LANGUAGE.EN,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.REGISTER.message,
		value: "Register success",
	},
	{
		lang: LANGUAGE.VI,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.REGISTER.message,
		value: "Dang ky thanh cong",
	},
	{
		lang: LANGUAGE.EN,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.LOGIN.message,
		value: "Login success",
	},
	{
		lang: LANGUAGE.VI,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.LOGIN.message,
		value: "Dang nhap thanh cong",
	},
	{
		lang: LANGUAGE.EN,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.USER_INFO.message,
		value: "Get user info success",
	},
	{
		lang: LANGUAGE.VI,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.USER_INFO.message,
		value: "Lay thong tin nguoi dung thanh cong",
	},
	{
		lang: LANGUAGE.EN,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.CREATE_SETTING.message,
		value: "Create setting success",
	},
	{
		lang: LANGUAGE.VI,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.CREATE_SETTING.message,
		value: "Tao cai dat thanh cong",
	},
	{
		lang: LANGUAGE.EN,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.GET_SETTING.message,
		value: "Get setting success",
	},
	{
		lang: LANGUAGE.VI,
		ns: TRANSLATION_NS.BACKEND,
		key: RES_KEY.GET_SETTING.message,
		value: "Lay cai dat thanh cong",
	},
];
