export const translates = [
	{
		lang: "en",
		ns: "translation",
		key: "ERROR.UNKNOWN",
		value: "Unknown error",
	},
	{
		lang: "vi",
		ns: "translation",
		key: "ERROR.UNKNOWN",
		value: "Loi khong xac dinh",
	},
	{
		lang: "en",
		ns: "translation",
		key: "ERROR.VALIDATION",
		value: "Validation data failed",
	},
	{
		lang: "vi",
		ns: "translation",
		key: "ERROR.VALIDATION",
		value: "Thong tin gui len khong hop le",
	},
	{
		lang: "en",
		ns: "translation",
		key: "ERROR.NOT_FOUND",
		value: "Not found",
	},
	{
		lang: "vi",
		ns: "translation",
		key: "ERROR.NOT_FOUND",
		value: "Khong tim thay duong dan",
	},
	{
		lang: "en",
		ns: "translation",
		key: "ERROR.INTERNAL_SERVER_ERROR",
		value: "Internal server error",
	},
	{
		lang: "vi",
		ns: "translation",
		key: "ERROR.INTERNAL_SERVER_ERROR",
		value: "Loi khong xac dinh",
	},
	{
		lang: "en",
		ns: "translation",
		key: "ERROR.UN_AUTHORIZATION",
		value: "Un authorization",
	},
	{
		lang: "vi",
		ns: "translation",
		key: "ERROR.UN_AUTHORIZATION",
		value: "Loi xac thuc nguoi dung",
	},
	{
		lang: "en",
		ns: "translation",
		key: "ERROR.EMAIL_ALREADY_EXIST",
		value: "Email already exist",
	},
	{
		lang: "vi",
		ns: "translation",
		key: "ERROR.EMAIL_ALREADY_EXIST",
		value: "Email da ton tai",
	},
	{
		lang: "en",
		ns: "translation",
		key: "ERROR.USERNAME_ALREADY_EXIST",
		value: "Username already exist",
	},
	{
		lang: "vi",
		ns: "translation",
		key: "ERROR.USERNAME_ALREADY_EXIST",
		value: "Username da ton tai",
	},
];
