name: Test
on:

  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Git sort sha
        run: echo ${{ steps.vars.outputs.sha_short }}

      - name: Setup bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install


      - name: Create env file
        run: |
          cp .env.example .env

      - name: Test
        run: bun test